"use client";
import { useState, useCallback, useEffect, useRef } from "react";
import { Calculator } from "@/data/calculators";
import { calculate, CalcResult } from "@/lib/calculations";
import { FieldRenderer } from "./FieldRenderer";
import { ResultsPanel } from "./ResultsPanel";
import { useLocalStorage } from "@/lib/hooks";
import { copyToClipboard, share } from "@/lib/utils";
import { Star, StarOff, Share2, RotateCcw, Zap } from "lucide-react";
import clsx from "clsx";

interface Props {
  calculator: Calculator;
}

export function CalculatorClient({ calculator }: Props) {
  // Build initial values from field defaults
  const getDefaults = () => {
    const defaults: Record<string, string> = {};
    calculator.fields.forEach((f) => {
      if (f.defaultValue !== undefined) defaults[f.id] = String(f.defaultValue);
    });
    return defaults;
  };

  const [values, setValues] = useState<Record<string, string>>(getDefaults);
  const [result, setResult] = useState<CalcResult | null>(null);
  const [shareStatus, setShareStatus] = useState<"idle" | "shared" | "copied">("idle");
  const [copiedResult, setCopiedResult] = useState(false);
  const resultRef = useRef<HTMLDivElement>(null);

  // Bookmarks via localStorage
  const [bookmarks, setBookmarks] = useLocalStorage<string[]>("uc_bookmarks", []);
  const isBookmarked = bookmarks.includes(calculator.slug);

  // Track recent visits
  const [, setRecent] = useLocalStorage<string[]>("uc_recent", []);
  useEffect(() => {
    setRecent((prev: string[]) =>
      [calculator.slug, ...prev.filter((s: string) => s !== calculator.slug)].slice(0, 10)
    );
  }, [calculator.slug, setRecent]);

  const handleChange = useCallback((id: string, val: string) => {
    setValues((prev) => ({ ...prev, [id]: val }));
    setResult(null);
  }, []);

  const handleCalculate = useCallback(() => {
    const res = calculate(calculator.formula, values);
    setResult(res);
    setTimeout(() => {
      resultRef.current?.scrollIntoView({ behavior: "smooth", block: "nearest" });
    }, 100);
  }, [calculator.formula, values]);

  const handleReset = () => {
    setValues(getDefaults());
    setResult(null);
  };

  const toggleBookmark = () => {
    setBookmarks((prev: string[]) =>
      prev.includes(calculator.slug)
        ? prev.filter((s: string) => s !== calculator.slug)
        : [...prev, calculator.slug]
    );
  };

  const handleCopyResult = async () => {
    if (!result || result.error) return;
    const text = [
      calculator.title,
      "─".repeat(40),
      ...result.outputs.map((r) => `${r.label}: ${r.value}`),
      "",
      "Generated by UrgentCalculate.com",
    ].join("\n");
    const ok = await copyToClipboard(text);
    if (ok) {
      setCopiedResult(true);
      setTimeout(() => setCopiedResult(false), 2500);
    }
  };

  const handleShare = async () => {
    const status = await share({
      title: calculator.title,
      text: calculator.description,
      url: window.location.href,
    });
    setShareStatus(status === "failed" ? "idle" : status);
    setTimeout(() => setShareStatus("idle"), 2500);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !(e.target instanceof HTMLTextAreaElement)) {
      e.preventDefault();
      handleCalculate();
    }
  };

  return (
    <div className="card overflow-hidden">
      {/* Card Header */}
      <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 dark:border-slate-700 bg-slate-50 dark:bg-slate-800/50">
        <div className="flex items-center gap-2">
          <span className="text-2xl">{calculator.icon}</span>
          <h2 className="font-semibold text-slate-900 dark:text-slate-100 text-sm sm:text-base">
            {calculator.title}
          </h2>
        </div>
        <div className="flex items-center gap-1">
          <button
            onClick={toggleBookmark}
            title={isBookmarked ? "Remove bookmark" : "Bookmark"}
            className="p-2 rounded-lg hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors"
          >
            {isBookmarked ? (
              <Star className="w-4 h-4 text-yellow-400 fill-yellow-400" />
            ) : (
              <StarOff className="w-4 h-4 text-slate-400" />
            )}
          </button>
          <button
            onClick={handleShare}
            title="Share this calculator"
            className="p-2 rounded-lg hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors flex items-center gap-1"
          >
            <Share2 className={clsx("w-4 h-4", shareStatus !== "idle" ? "text-green-500" : "text-slate-400")} />
          </button>
          {shareStatus !== "idle" && (
            <span className="text-xs text-green-600 font-medium">
              {shareStatus === "shared" ? "Shared!" : "Link copied!"}
            </span>
          )}
        </div>
      </div>

      {/* Fields */}
      <div className="p-6" onKeyDown={handleKeyDown}>
        <div className="grid sm:grid-cols-2 gap-5">
          {calculator.fields.map((field) => (
            <FieldRenderer
              key={field.id}
              field={field}
              value={values[field.id] ?? ""}
              onChange={(val) => handleChange(field.id, val)}
            />
          ))}
        </div>

        <div className="flex gap-3 mt-7">
          <button
            onClick={handleCalculate}
            className="btn-primary flex-1 h-12 text-base flex items-center justify-center gap-2"
          >
            <Zap className="w-4 h-4" />
            Calculate
          </button>
          <button
            onClick={handleReset}
            className="btn-secondary flex items-center gap-2 px-5 h-12"
            title="Reset all fields"
          >
            <RotateCcw className="w-4 h-4" />
            <span className="hidden sm:inline">Reset</span>
          </button>
        </div>

        <p className="text-xs text-slate-400 mt-3 text-center">
          Press <kbd className="px-1.5 py-0.5 bg-slate-100 dark:bg-slate-700 rounded text-slate-500 font-mono">Enter</kbd> to calculate
        </p>
      </div>

      {result && (
        <div ref={resultRef} className="animate-fadeIn">
          <ResultsPanel result={result} onCopy={handleCopyResult} copied={copiedResult} />
        </div>
      )}
    </div>
  );
}
